name: environment
channels:
- conda-forge
- defaults
dependencies:
- attr==0.3.2
- colorama==0.4.6
- ConfigParser==7.1.0
- cryptography==44.0.1
- Cython==3.0.12
- dl==0.1.0
- docutils==0.21.2
- filelock==3.17.0
- HTMLParser==0.0.2
- huggingface_hub==0.28.1
- ipykernel==6.29.5
- ipython==8.12.3
- ipywidgets==8.1.5
- keyring==25.6.0
- langchain_community==0.3.17
- langchain_text_splitters==0.3.6
- matplotlib==3.10.0
- numpy>=1.26.4
- ordereddict==1.1
- pandas==2.2.3
- Pillow==11.1.0
- protobuf==5.29.3
- pymilvus==2.5.4
- pyOpenSSL==25.0.0
- pypdf==5.3.0
- redis==5.2.1
- scikit_learn==1.6.1
- sentence_transformers==3.4.1
- thread==2.0.5
- torch==2.6.0
- torchsummary==1.5.1
- torchvision==0.21.0
- tqdm==4.67.1
- urllib3_secure_extra==0.1.0
